version: '3.8'

services:
  scheduler:
    build: ./scheduler
    networks:
      - my-network
    depends_on:
      - scraper-presse-citron

  scraper-presse-citron:
    build: ./Scrapers/scraper-presse-citron
    networks:
      - my-network
    ports:
      - "3000:3000"

  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data:
