version: '3'
services:
  postgres:
    container_name: claire_postgres
    image: postgres
    environment:
      POSTGRES_DB: claire_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@postgres/claire_db
    depends_on:
      - postgres

volumes:
  db_data:
